### ISSUE TITLE
How to create a cluster when we do not have a global API key?

### ISSUE THREAD

**Issue by thanos1983** [qdrant/terraform-provider-qdrant-cloud#20]
I have just started experimenting with the module [qdrant/qdrant-cloud](https://registry.terraform.io/providers/qdrant/qdrant-cloud/latest/docs). I am having difficulty to understand how to authenticate through the Terraform module.

I am using the provider for example:

```bash
provider "qdrant-cloud" {
  api_key    = "" // API Key generated in Qdrant Cloud (required)
  account_id = "" // The default account ID you want to use in Qdrant Cloud (can be overriden on resource level)
}
```

The `api_key` can only be provided by the UI when the user creates a cluster (manually). How can a user create a cluster with a global API Key? Is there a way that we can retrieve a global API Key?

PS: I tried the code above with an existing cluster and I am getting unauthorized 401. What am I doing wrong?

**Comment by bashofmann** [comment]
The terraform provider requires an account API key (not a database api key) for authentication. It's not possible yet to create these account API keys, because the public API and the Terraform Provider is currently in Closed Beta. 

To learn more please and potentially join the beta [Contact Us](https://qdrant.tech/contact-us/).
